### ISSUE TITLE
Todo: Super Low Spec Mode

### ISSUE THREAD

**Issue by nomi-san** [PenguLoader/PenguLoader#17]
Enable this option to disable all transition and animation effects in League Client.

- [x] Super Low Spec Mode option
- [x] Beat terrible #shadow-root 😢

```css
* {
  -webkit-transition: none !important;
  -webkit-animation: none !important;
  transition: none !important;
  animation: none !important;
}
```
